/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.House;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
import model.City;
import model.Community;

/**
 *
 * @author mohithparvataneni
 */
public class PersonPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonPanel
     */
    DefaultTableModel model;
    int row,col;
    private PersonDirectory personDirectory;
    private Person person;
    
    
    public PersonPanel(PersonDirectory personDirectory) {
        initComponents();
        this.personDirectory = personDirectory;
        model = (DefaultTableModel) personTable.getModel();
        btnGroupSex.add(btnMale);
        btnGroupSex.add(btnFemale);
        btnGroupMaritalStatus.add(btnSingle);
        btnGroupMaritalStatus.add(btnMarried);
        //readCSV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSex = new javax.swing.ButtonGroup();
        btnGroupMaritalStatus = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        boxCommunity = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSingle = new javax.swing.JRadioButton();
        btnMarried = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        btnAddPerson = new javax.swing.JButton();
        btnUpdatePerson = new javax.swing.JButton();
        btnDeletePerson = new javax.swing.JButton();
        btnViewPersons = new javax.swing.JButton();
        btnClearPerson = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        txtHno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSearchFname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSearchLname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnSearchPerson = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        boxSearchCommunity = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setText("First Name");

        jLabel4.setText("Age");

        jLabel6.setText("Sex");

        btnMale.setText("Male");

        btnFemale.setText("Female");

        jLabel7.setText("Community");

        boxCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Boylston", "Roxbury", "Fenway", "Prudential" }));

        jLabel8.setText("House Number");

        jLabel9.setText("Marital Status");

        btnSingle.setText("Single");

        btnMarried.setText("Married");

        jLabel10.setText("City");

        jLabel11.setText("State");

        jLabel12.setText("Zip Code");

        jLabel13.setText("Phone Number");

        btnAddPerson.setText("Add");
        btnAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonActionPerformed(evt);
            }
        });

        btnUpdatePerson.setText("Update");
        btnUpdatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePersonActionPerformed(evt);
            }
        });

        btnDeletePerson.setText("Delete");
        btnDeletePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePersonActionPerformed(evt);
            }
        });

        btnViewPersons.setText("View");
        btnViewPersons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPersonsActionPerformed(evt);
            }
        });

        btnClearPerson.setText("Clear");
        btnClearPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPersonActionPerformed(evt);
            }
        });

        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Age", "Sex", "H:No", "Street", "Community", "City", "State", "Zip Code", "Contact", "Marital Status"
            }
        ));
        personTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(personTable);

        jLabel1.setText("Last Name");

        jLabel14.setText("Street Name");

        jLabel5.setText("First Name");

        jLabel15.setText("Last Name");

        jLabel16.setText("Community");

        btnSearchPerson.setText("Search");
        btnSearchPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPersonActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 0));
        jLabel18.setText("Person Search");

        boxSearchCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Boylston", "Roxbury", "Fenway", "Prudential" }));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Manage Person Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAddPerson)
                                .addGap(18, 18, 18)
                                .addComponent(btnViewPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdatePerson)
                                .addGap(213, 213, 213))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(92, 92, 92)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMale)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnFemale)
                                    .addComponent(txtHno, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnSingle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnMarried)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(btnDeletePerson)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnClearPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtZip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel5))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearchFname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSearchLname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxSearchCommunity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(btnSearchPerson)))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnMale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFemale)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(boxCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtSearchFname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSearchLname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnSingle)
                    .addComponent(btnMarried)
                    .addComponent(jLabel16)
                    .addComponent(boxSearchCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdatePerson)
                    .addComponent(btnDeletePerson)
                    .addComponent(btnViewPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddPerson)
                    .addComponent(btnClearPerson)
                    .addComponent(btnSearchPerson))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1099, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonActionPerformed

        String firstName = txtFname.getText();
        String lastName = txtLname.getText();
        String strAge = txtAge.getText();
        String sex = getSex();
        String houseNumber = txtHno.getText();
        String streetName = txtStreet.getText();
        String strCommunity = boxCommunity.getSelectedItem().toString();
        String strCity = txtCity.getText();
        String state = txtState.getText();
        String strZipCode = txtZip.getText();
        String phoneNo = txtPhone.getText();
        String maritalStatus = getMartialStatus();
        
        if (!isNumber(strAge))
        {
            JOptionPane.showMessageDialog(null,"Invalid Age. Please insert a number");
            return;
        }
        
        if (!isNumber(strZipCode))
        {
            JOptionPane.showMessageDialog(null,"Invalid Zip Code. Please insert a number");
            return;
        }
        
        if (!phoneNo.matches("^\\d{10}$"))
        {
            JOptionPane.showMessageDialog(null,"Enter a valid phone number");
            return;
        }
        
        if (firstName.isEmpty()||lastName.isEmpty()||strAge.isEmpty()|| houseNumber.isEmpty()
            || streetName.isEmpty() || strCommunity.isEmpty() || strCity.isEmpty()
            || state.isEmpty() || strZipCode.isEmpty() || phoneNo.isEmpty() || sex.isEmpty() || maritalStatus.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "One or More fields are empty..!", "Empty Fields", 2);
        }
        else
        {
            int age = Integer.parseInt(strAge);
            int zipcode = Integer.parseInt(strZipCode);
            City city = new City(strCity);
            Community community = new Community(strCommunity, city);
            House house = new House(houseNumber,streetName,community,state,zipcode);
            Person person = new Person(firstName, lastName, phoneNo, sex, age, house, maritalStatus);
            personDirectory.addPerson(person);

            displayPersons(personDirectory.getPersonDirectory());

            JOptionPane.showMessageDialog(this, "Person information added successfully.!!", "Added person",1);
            clearField();
        }
    }//GEN-LAST:event_btnAddPersonActionPerformed

    private void btnUpdatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePersonActionPerformed

        String updatefirstName = txtFname.getText();
        String updatelastName = txtLname.getText();
        String updatestrAge = txtAge.getText();
        String updatesex = getSex();
        String updateHno = txtHno.getText();
        String updatestreetName = txtStreet.getText();
        String updatecommunity = boxCommunity.getSelectedItem().toString();
        String updatecity = txtCity.getText();
        String updatestate = txtState.getText();
        String updatestrzipCode = txtZip.getText();
        String updatephoneNo = txtPhone.getText();
        String updateMaritalStatus = getMartialStatus();
        
        if (!isNumber(updatestrAge))
        {
            JOptionPane.showMessageDialog(null,"Invalid Age. Please insert a number to update");
        }
        
        if (!isNumber(updatestrzipCode))
        {
            JOptionPane.showMessageDialog(null,"Invalid Zip Code. Please insert a number to update");
        }
        
        if (!updatephoneNo.matches("^\\d{10}$"))
        {
            JOptionPane.showMessageDialog(null,"Enter a valid phone number to update");
            return;
        }
        
        int updateage = Integer.parseInt(updatestrAge);
        int updatezip = Integer.parseInt(updatestrzipCode);

        if (txtFname.getText().isEmpty()||txtLname.getText().isEmpty()||txtAge.getText().isEmpty()|| txtHno.getText().isEmpty()
            || txtStreet.getText().isEmpty() || boxCommunity.getSelectedItem().toString().isEmpty() || txtCity.getText().isEmpty()
            || txtState.getText().isEmpty() || txtZip.getText().isEmpty() || txtPhone.getText().isEmpty() || updatesex.isEmpty() || updateMaritalStatus.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "One or More fields are empty..!", "Empty Fields",2);
        }

        else
        {

            City city = new City(updatecity);
            Community community = new Community(updatecommunity, city);
            House house = new House(updateHno,updatestreetName,community,updatestate,updatezip);

            personDirectory.getPersonDirectory().get(row).setFirstName(updatefirstName);
            personDirectory.getPersonDirectory().get(row).setLastName(updatelastName);
            personDirectory.getPersonDirectory().get(row).setAge(updateage);
            personDirectory.getPersonDirectory().get(row).setSex(updatesex);
            personDirectory.getPersonDirectory().get(row).setHouse(house);
            personDirectory.getPersonDirectory().get(row).setPhoneNumber(updatephoneNo);
            personDirectory.getPersonDirectory().get(row).setMaritalStatus(updateMaritalStatus);

            displayPersons(personDirectory.getPersonDirectory());

            JOptionPane.showMessageDialog(this, "Person information updated successfully.!!", "Updated person",1);
            clearField();
        }
    }//GEN-LAST:event_btnUpdatePersonActionPerformed

    private void btnDeletePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePersonActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Delete this data", "Delete", dialogButton);
        if (dialogResult == 0)
        {
            row = personTable.getSelectedRow();
            model.removeRow(row);
            personDirectory.getPersonDirectory().remove(row);
            model.setRowCount(0);
            displayPersons(personDirectory.getPersonDirectory());
            clearField();
        }
    }//GEN-LAST:event_btnDeletePersonActionPerformed

    private void btnViewPersonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPersonsActionPerformed

        displayPersons(personDirectory.getPersonDirectory());

    }//GEN-LAST:event_btnViewPersonsActionPerformed

    private void btnClearPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPersonActionPerformed
        model.setRowCount(0);
        clearField();
    }//GEN-LAST:event_btnClearPersonActionPerformed

    private void personTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personTableMouseClicked

        row = personTable.getSelectedRow();
        col = personTable.getColumnCount();

        txtFname.setText(model.getValueAt(row, 0).toString());
        txtLname.setText(model.getValueAt(row, 1).toString());
        txtAge.setText(model.getValueAt(row, 2).toString());
        txtHno.setText(model.getValueAt(row, 4).toString());
        txtStreet.setText(model.getValueAt(row, 5).toString());
        boxCommunity.setSelectedItem(model.getValueAt(row, 6).toString());
        txtCity.setText(model.getValueAt(row, 7).toString());
        txtState.setText(model.getValueAt(row, 8).toString());
        txtZip.setText(model.getValueAt(row, 9).toString());
        txtPhone.setText(model.getValueAt(row, 10).toString());
        if (model.getValueAt(row, 3).toString().equals("Male"))
        {
            btnMale.doClick();
        }
        if (model.getValueAt(row, 3).toString().equals("Female"))
        {
            btnFemale.doClick();
        }
        if (model.getValueAt(row, 11).toString().equals("Single"))
        {
            btnSingle.doClick();
        }
        if (model.getValueAt(row, 11).toString().equals("Married"))
        {
            btnMarried.doClick();
        }

    }//GEN-LAST:event_personTableMouseClicked

    private void btnSearchPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPersonActionPerformed
        
        String fName = txtSearchFname.getText();
        String lName = txtSearchLname.getText();
        String community = boxSearchCommunity.getSelectedItem().toString();
        List<Person> searchedList= new ArrayList<>();
        
        if(fName.isEmpty() && lName.isEmpty() && community.equals("None")){
            JOptionPane.showMessageDialog(this, "All search fields are empty.!! Please check", "Empty Fields", 2);
            
        }
        else{
            
            for(Person person : personDirectory.getPersonDirectory()){
                House house = person.getHouse();
                if(community.equals("None") || community.equals(house.getCommunity())){
                    if((fName.isEmpty() || fName.equalsIgnoreCase(person.getFirstName())) && (lName.isEmpty() || lName.equalsIgnoreCase(person.getLastName())))
                        searchedList.add(person);
                }
            }
            
            
        }
        
        model.setRowCount(0);
        displayPersons(searchedList);
    }//GEN-LAST:event_btnSearchPersonActionPerformed
 public void clearField(){
        
        
        txtFname.setText("");
        txtLname.setText("");
        txtAge.setText("");
        btnGroupSex.clearSelection();
        txtHno.setText("");
        txtStreet.setText("");
        boxCommunity.setSelectedIndex(0);
        txtCity.setText("");
        txtState.setText("");
        txtZip.setText("");
        txtPhone.setText("");
        btnGroupMaritalStatus.clearSelection();
        clearSearch();
        
    }
    public void clearSearch(){
        txtSearchFname.setText("");
        txtSearchLname.setText("");
        boxSearchCommunity.setSelectedIndex(0);
    }
    public  void displayPersons(List<Person> persons){
        model.setRowCount(0);
        for(Person person : persons){
            House house = person.getHouse();
            Community community = house.getCommunity();
            
            Object[] objs = {person.getFirstName(), person.getLastName(), person.getAge(), person.getSex(), house.getHno(),house.getStreet(),community.getCommunityName(),community.getCity().getCityName(),house.getState(),house.getZipcode(),person.getPhoneNumber(),person.getMaritalStatus()};
            model.addRow(objs);
        }
        
    }
    public String getSex(){
        
        if(btnMale.isSelected()) return "Male";
        else if(btnFemale.isSelected()) return "Female";
        return "";
    }
    
    public String getMartialStatus(){
        
        if(btnSingle.isSelected()) return "Single";
        else if(btnMarried.isSelected()) return "Married";
        return "";
    }
    
    
     private static boolean isNumber(String n) {
		try {
			Integer.parseInt(n);
			return true;
		} catch (NumberFormatException nfe) {
			return false;
		}
	}
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCommunity;
    private javax.swing.JComboBox<String> boxSearchCommunity;
    private javax.swing.JButton btnAddPerson;
    private javax.swing.JButton btnClearPerson;
    private javax.swing.JButton btnDeletePerson;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.ButtonGroup btnGroupMaritalStatus;
    private javax.swing.ButtonGroup btnGroupSex;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JRadioButton btnMarried;
    private javax.swing.JButton btnSearchPerson;
    private javax.swing.JRadioButton btnSingle;
    private javax.swing.JButton btnUpdatePerson;
    private javax.swing.JButton btnViewPersons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable personTable;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtHno;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearchFname;
    private javax.swing.JTextField txtSearchLname;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
