/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Restaurant.Restaurant;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mohithparvataneni
 */
public class ManageRestaurantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestaurantJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    DefaultTableModel model;
    int row,col;
    public ManageRestaurantJPanel(JPanel userProcessContainer, EcoSystem system ) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system = system;
        model = (DefaultTableModel) tableRestaurant.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtManager = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        boxLocation = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRestaurant = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnUpdateRestaurant = new javax.swing.JButton();
        btnDeleteRestaurant = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        jLabel1.setText("Restaurant Name");

        jLabel2.setText("Location");

        jLabel3.setText("Manager Name");

        jLabel4.setText("UserName");

        jLabel5.setText("Password");

        boxLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Boylston", "Cambridge", "Malden", "Roxbury", "Somerville" }));

        tableRestaurant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant Name", "Location", "Manager", "Username", "Password"
            }
        ));
        tableRestaurant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRestaurantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRestaurant);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdateRestaurant.setText("Update");
        btnUpdateRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRestaurantActionPerformed(evt);
            }
        });

        btnDeleteRestaurant.setText("Delete");
        btnDeleteRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRestaurantActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSave)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName)
                                    .addComponent(txtManager)
                                    .addComponent(txtUserName)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateRestaurant)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteRestaurant)
                                .addGap(18, 18, 18)
                                .addComponent(btnView))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(boxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManager, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdateRestaurant)
                    .addComponent(btnDeleteRestaurant)
                    .addComponent(btnView))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String name = txtName.getText();
        String location = boxLocation.getSelectedItem().toString();
        String mgr = txtManager.getText();
        String user = txtUserName.getText();
        String pwd = txtPassword.getText();

        if (name.isEmpty()|| location.isEmpty() || mgr.isEmpty() || user.isEmpty() || pwd.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "One or More fields are empty..!", "Empty Fields", 2);
            return;
        }


        if (!system.getRestaurantDirectory().checkIfRestaurantisUnique(name))
        {
            JOptionPane.showMessageDialog(this,"Restaurant name already exits!!...please select a different username","Restaurant exists", 2);
            return;
        }
        
        if (!system.getUserAccountDirectory().checkIfUsernameIsUnique(user))
        {
            JOptionPane.showMessageDialog(this,"User ID exits...please select a different username","User Exists", 2);
            return;
        }
        
        
        Employee employee = new Employee();
        employee.setName(mgr);
        AdminRole role = new AdminRole();
        UserAccount userAccount =  system.getUserAccountDirectory().createUserAccount(user, pwd, employee,role);
        //System.out.println(userAccount);

        Restaurant restaurant = new Restaurant(name, location, userAccount);
        system.getRestaurantDirectory().addRestaurant(restaurant);
        system.getUserAccountDirectory().createUserAccount(user, pwd, employee, role);

        displayRestaurant();

        JOptionPane.showMessageDialog(this, "Restaurant information added successfully.!!", "Added Restaurant",1);
        clearField();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRestaurantActionPerformed
        
        String updateRestaurantName = txtName.getText();
        String updateLocation = boxLocation.getSelectedItem().toString();
        String updateManagerName = txtManager.getText();
        String updateUserName = txtUserName.getText();
        String updatePassword = txtPassword.getText();
        
         if(updateRestaurantName.isEmpty() || updateLocation.isEmpty() || updateManagerName.isEmpty() || updateUserName.isEmpty() || updatePassword.isEmpty()) {
            JOptionPane.showMessageDialog(this,"One or more fields are empty. Please check..||");
            return;
        }
        
        Employee employee = new Employee();
        employee.setName(updateManagerName);
        AdminRole role = new AdminRole();
        UserAccount userAccount =  system.getUserAccountDirectory().createUserAccount(updateUserName, updatePassword, employee,role);
        Restaurant restaurant = new Restaurant(updateRestaurantName, updateLocation, userAccount);
        
        system.getRestaurantDirectory().getRestaurantList().get(row).setRestaurantName(updateRestaurantName);
        system.getRestaurantDirectory().getRestaurantList().get(row).setLocation(updateLocation);
        
        displayRestaurant();
        JOptionPane.showMessageDialog(this, "Restaurant information updated successfully.!!", "updated restaurant",1);
        clearField();
    }//GEN-LAST:event_btnUpdateRestaurantActionPerformed

    private void btnDeleteRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRestaurantActionPerformed
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Delete this data", "Delete", dialogButton);
        if (dialogResult == 0)
        {
            row = tableRestaurant.getSelectedRow();
            system.getRestaurantDirectory().getRestaurantList().remove(row);
            String UserName = model.getValueAt(row, 3).toString();
            system.getUserAccountDirectory().removeUserAccount(UserName);
            displayRestaurant();
            clearField();
        }
        
    }//GEN-LAST:event_btnDeleteRestaurantActionPerformed

    private void tableRestaurantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRestaurantMouseClicked
        
        row = tableRestaurant.getSelectedRow();
        col = tableRestaurant.getSelectedColumn();
        
        txtName.setText(model.getValueAt(row, 0).toString());
        boxLocation.setSelectedItem(model.getValueAt(row, 1).toString());
        txtManager.setText(model.getValueAt(row, 2).toString());
        txtUserName.setText(model.getValueAt(row, 3).toString());
        txtPassword.setText(model.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tableRestaurantMouseClicked

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        displayRestaurant();
    }//GEN-LAST:event_btnViewActionPerformed
    
    public  void displayRestaurant(){
        
        model.setRowCount(0);
        
        for(Restaurant restaurant : system.getRestaurantDirectory().getRestaurantList()){    
            
            Object[] objs = {restaurant.getRestaurantName(),restaurant.getLocation(),restaurant.getUserAccount().getEmployee().getName(),restaurant.getUserAccount().getUsername(),restaurant.getUserAccount().getPassword()};
            model.addRow(objs);
        }
        
    }
    
    public void clearField(){
        
        txtName.setText("");
        boxLocation.setSelectedIndex(0);
        txtManager.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxLocation;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteRestaurant;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateRestaurant;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRestaurant;
    private javax.swing.JTextField txtManager;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
