/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mohithparvataneni
 */
public class ManageDeliveryManJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDeliveryManJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    DefaultTableModel model;
    int row,col;
    public ManageDeliveryManJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        btnGroupSex.add(btnMale);
        btnGroupSex.add(btnFemale);
        model = (DefaultTableModel) tableDeliveryMan.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSex = new javax.swing.ButtonGroup();
        txtMail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDeliveryMan = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtContact = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtpwd = new javax.swing.JTextField();
        btnUpdateDeliveryMan = new javax.swing.JButton();
        btnDeleteDeliveryMan = new javax.swing.JButton();
        btnViewDeliveryMen = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        tableDeliveryMan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Sex", "Mail ID", "Contact", "Username", "Password"
            }
        ));
        tableDeliveryMan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDeliveryManMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableDeliveryMan);

        jLabel5.setText("Contact");

        btnBack.setBackground(new java.awt.Color(102, 204, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        btnSave.setBackground(new java.awt.Color(102, 204, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel2.setText("Age");

        jLabel3.setText("Sex");

        btnMale.setText("Male");

        btnFemale.setText("Female");

        jLabel6.setText("Username");

        jLabel4.setText("Mail ID");

        jLabel7.setText("Password");

        btnUpdateDeliveryMan.setBackground(new java.awt.Color(102, 204, 255));
        btnUpdateDeliveryMan.setText("Update");
        btnUpdateDeliveryMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDeliveryManActionPerformed(evt);
            }
        });

        btnDeleteDeliveryMan.setBackground(new java.awt.Color(102, 204, 255));
        btnDeleteDeliveryMan.setText("Delete");
        btnDeleteDeliveryMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDeliveryManActionPerformed(evt);
            }
        });

        btnViewDeliveryMen.setBackground(new java.awt.Color(102, 204, 255));
        btnViewDeliveryMen.setText("View");
        btnViewDeliveryMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDeliveryMenActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Manage Delivery Man");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateDeliveryMan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteDeliveryMan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewDeliveryMen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(btnBack)
                            .addGap(120, 120, 120)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(235, 235, 235)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(86, 86, 86)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnMale)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnFemale))
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtUser, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpwd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnMale)
                    .addComponent(btnFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdateDeliveryMan)
                    .addComponent(btnDeleteDeliveryMan)
                    .addComponent(btnViewDeliveryMen))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        String strAge = txtAge.getText();
        String sex = getSex();
        String mail = txtMail.getText();
        String contact = txtContact.getText();
        String user = txtUser.getText();
        String pwd = txtpwd.getText();

        if (name.isEmpty()||strAge.isEmpty() || sex.isEmpty() || mail.isEmpty() || contact.isEmpty() || user.isEmpty() || pwd.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "One or More fields are empty..!", "Empty Fields", 2);
            return;
        }

        if (!isNumber(strAge))
        {
            JOptionPane.showMessageDialog(this,"Invalid Age. Please insert a number","Invalid age", 2);
            return;
        }

        if (!contact.matches("^\\d{10}$"))
        {
            JOptionPane.showMessageDialog(this,"Enter a valid phone number","invalid contact", 2);
            return;
        }

    
        if (!system.getUserAccountDirectory().checkIfUsernameIsUnique(user))
        {
            JOptionPane.showMessageDialog(this,"User ID exits...please select a different username","User already exist",2);
            return;
        }
        

        int age = Integer.parseInt(strAge);

        DeliveryMan deliveryMan = new DeliveryMan(name, age, sex, mail, contact, user, pwd);
        system.getDeliveryManDirectory().addDeliveryMan(deliveryMan);
        system.getUserAccountDirectory().createDeliverymanAccount(user, pwd, deliveryMan);
        displayDeliveryMen();

        JOptionPane.showMessageDialog(this, "DeliveryMan information added successfully.!!", "Added DeliveryMan",1);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateDeliveryManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDeliveryManActionPerformed
        
        String updatename = txtName.getText();
        String updatestrAge = txtAge.getText();
        String updatesex = getSex();
        String updatemail = txtMail.getText();
        String updatecontact = txtContact.getText();
        String updateuser = txtUser.getText();
        String updatepwd = txtpwd.getText();
        
        if (updatename.isEmpty()||updatestrAge.isEmpty() || updatesex.isEmpty() || updatemail.isEmpty() || updatecontact.isEmpty() || updateuser.isEmpty() || updatepwd.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "One or More fields are empty..!", "Empty Fields", 2);
            return;
        }
        
        if (!isNumber(updatestrAge))
        {
            JOptionPane.showMessageDialog(this,"Invalid Age. Please insert a number");
            return;
        }
        
        if (!updatecontact.matches("^\\d{10}$"))
        {
            JOptionPane.showMessageDialog(this,"Enter a valid phone number");
            return;
        }
        
//        if (!system.getUserAccountDirectory().checkIfUsernameIsUnique(updateuser))
//        {
//            JOptionPane.showMessageDialog(null,"User ID exits...please select a different username");
//            return;
//        }
        
        int updateage = Integer.parseInt(updatestrAge);
        String username = model.getValueAt(row, 5).toString();
        
       
        system.getUserAccountDirectory().removeUserAccount(username);
        
        //DeliveryMan deliveryMan = new DeliveryMan(updatename, updateage, updatesex, updatemail, updatecontact, updateuser, updatepwd);
        
        system.getDeliveryManDirectory().getDeliveryManList().get(row).setName(updatename);
        system.getDeliveryManDirectory().getDeliveryManList().get(row).setAge(updateage);
        system.getDeliveryManDirectory().getDeliveryManList().get(row).setGender(updatesex);
        system.getDeliveryManDirectory().getDeliveryManList().get(row).setEmail(updatemail);
        system.getDeliveryManDirectory().getDeliveryManList().get(row).setContact(updatecontact);
        //system.getCustomerDirectory().getcustomerList().get(row).setUserName(updateuser);
        //txtUser.setEditable(false);
        system.getDeliveryManDirectory().getDeliveryManList().get(row).setPassword(updatepwd);
        
        DeliveryMan deliveryMan = system.getDeliveryManDirectory().getDeliveryManList().get(row);

        system.getUserAccountDirectory().createDeliverymanAccount(updateuser, updatepwd, deliveryMan);
        
        if (!username.equals(updateuser))
        {
           JOptionPane.showMessageDialog(this, "username cannot be changed", "change username", 2);
           return;
        }
        
        displayDeliveryMen();

        JOptionPane.showMessageDialog(this, "Delivery man information updated successfully.!!", "updated delivery man",1);
        clearField();
    }//GEN-LAST:event_btnUpdateDeliveryManActionPerformed

    private void btnDeleteDeliveryManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDeliveryManActionPerformed
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Delete this data", "Delete", dialogButton);
        if (dialogResult == 0)
        {
            row = tableDeliveryMan.getSelectedRow();
            system.getDeliveryManDirectory().getDeliveryManList().remove(row);
            String UserName = model.getValueAt(row, 5).toString();
            system.getUserAccountDirectory().removeUserAccount(UserName);
            displayDeliveryMen();
            clearField();
        }
    }//GEN-LAST:event_btnDeleteDeliveryManActionPerformed

    private void btnViewDeliveryMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDeliveryMenActionPerformed
        
        displayDeliveryMen();
    }//GEN-LAST:event_btnViewDeliveryMenActionPerformed

    private void tableDeliveryManMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDeliveryManMouseClicked
       
        row = tableDeliveryMan.getSelectedRow();
        col = tableDeliveryMan.getColumnCount();
        
        txtName.setText(model.getValueAt(row, 0).toString());
        txtAge.setText(model.getValueAt(row, 1).toString());
        if (model.getValueAt(row, 2).toString().equals("Male"))
        {
            btnMale.doClick();
        }
        if (model.getValueAt(row, 2).toString().equals("Female"))
        {
            btnFemale.doClick();
        }
        txtMail.setText(model.getValueAt(row, 3).toString());
        txtContact.setText(model.getValueAt(row, 4).toString());
        txtUser.setText(model.getValueAt(row, 5).toString());
        txtpwd.setText(model.getValueAt(row, 6).toString());
    }//GEN-LAST:event_tableDeliveryManMouseClicked
    
    public String getSex(){
        
        if(btnMale.isSelected()) return "Male";
        else if(btnFemale.isSelected()) return "Female";
        return "";
    }
    
    private static boolean isNumber(String n) {
		try {
			Integer.parseInt(n);
			return true;
		} catch (NumberFormatException nfe) {
			return false;
		}
    }
    
    public void clearField(){
        
        txtName.setText("");
        txtAge.setText("");
        txtMail.setText("");
        txtContact.setText("");
        txtUser.setText("");
        txtpwd.setText("");
        btnGroupSex.clearSelection();
    }
    
    public  void displayDeliveryMen(){
        
        model.setRowCount(0);
        
        for(DeliveryMan deliveryMan : system.getDeliveryManDirectory().getDeliveryManList()){            
            Object[] objs = {deliveryMan.getName(),deliveryMan.getAge(),deliveryMan.getGender(),deliveryMan.getEmail(),deliveryMan.getContact(),deliveryMan.getUserName(),deliveryMan.getPassword()};
            model.addRow(objs);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteDeliveryMan;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.ButtonGroup btnGroupSex;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateDeliveryMan;
    private javax.swing.JButton btnViewDeliveryMen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableDeliveryMan;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtpwd;
    // End of variables declaration//GEN-END:variables
}
